import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import { getProviders, getSession, useSession } from "next-auth/react";
import Login from '../components/Login';
import Modal from '../components/Modal';
import { useRecoilState } from 'recoil';
import { modalState } from '../atoms/modalAtom';

export default function Home({ trendingResults, followResults, providers }) {
  const {data: session} = useSession();
  const [isOpen,setIsOpen] = useRecoilState(modalState)

  if (!session) return <Login providers={providers} />;
  
  return (
    <div className="">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        <Sidebar/>
        {/* Feed */}
        <Feed/>
        {/* Widgets */}

        {/* Modal */}
        {isOpen && <Modal />}
        <Modal/>
        {/*only display modal if my isOpen state is true  */} 
      </main>
      </div>
  )
}

export async function getServerSideProps(context) {
  const trendingResults = await fetch("https://www.jsonkeeper.com/b/NKEV").then(//api endpoint
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(//api endpoint
    (res) => res.json()
  );
  const providers = await getProviders();
  console.log(providers)
  const session = await getSession(context);// get rid of flickering of login page

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
      //prevents flickering of login (in react app)
    },
  };
}
